#! /bin/bash

for program in $*; do
    echo -n "$(basename $program)"
    cat tests | while read -r line; do
        result=$(echo $line | cut -d" " -f1)
        input=$(echo $line  | cut -d" " -s -f2-)

        echo -n "   "
        # Output Strict : if echo $input | ./$program | grep "$result parenthesage" >/dev/null 2>&1; then
        if echo $input | ./$program | grep $result >/dev/null 2>&1; then
            echo -n "  OK"
        else
            echo -n "XXXX"
        fi
    done

    echo ""
done
